### ISSUE TITLE
Allow content paths to use glob patterns (again)

### ISSUE THREAD

**Issue by uglow** [swanky-docs/swanky-server#38]
Release 1.14.0 broke support for the following swanky config:
```
sections:
  - title: Everything
    content: docs/**/*.md  #This works because swanky-webpack-plugin is processing MD files using globs
  - title: API
    content: src/**/*.js
```

The sections[ ].content property is currently being treated as a string, not as a glob.
